version: "2"
services:
  web:
    build: .
    ports:
    - "3000:3000"
    depends_on:
    - mongo
    container_name: node
    
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    hostname: mongo
    